set(CPACK_PACKAGE_DESCRIPTION "UcoSLAM Package")
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_VENDOR "University of Cordoba")
set(CPACK_PACKAGE_CONTACT "rmsalinas@uco.es")


execute_process(COMMAND lsb_release -a COMMAND grep Release:  COMMAND  cut -f2 OUTPUT_VARIABLE RELEASE_CODENAME OUTPUT_STRIP_TRAILING_WHITESPACE)
set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}_ubuntu${RELEASE_CODENAME}")
SET(CPACK_PACKAGE_DESCRIPTION "UcoSLAM library and applications")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "UcoSLAM is a library for Simultaneous Localization and Mapping")

SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")

SET(CPACK_GENERATOR "DEB")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "i386")
SET(CPACK_DEBIAN_PACKAGE_DEPENDS " python-opencv, libqt5gui5, libqt5opengl5 ")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")

#set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

include (CPack)
#In Ubuntu 18 requires sudo apt-get install libopencv-highgui3.2 libopencv-calib3d3.2 libopencv-imgproc3.2 libqt5gui5 libqt5opengl5
